[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
allow = [
  "MIT",
  # unicode-ident's generated Unicode data is under this SPDX license.
  "Unicode-3.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
